# Server Configuration
server.port=${PORT:8080}

# Database Configuration - PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8dvk7k2n8qs738f83e8-a.ohio-postgres.render.com:5432/taskflow_db_c49z
spring.datasource.username=taskflow_user
spring.datasource.password=8CR8zzC114uNgwGn0FACi81NU0Hshh1Q
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=bXlTZWNyZXRLZXlGb3JKV1RNaW5pbXVtTGVuZ3RoSXMyNTZCaXRz
app.jwt.expiration=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.com.Springboot.TaskFlowApplication=DEBUG
